import PDFDocument from "pdfkit";
import Sale from "../models/Sale.js";
import Purchase from "../models/Purchase.js";
import Customer from "../models/Customer.js";
import { getISTStartOfDayUTC, getISTEndOfDayUTC } from "../utils/istDate.js";
import { getISTMonthStartUTC } from "../utils/istDate.js";

/* ================= COMMON HEADER ================= */
const drawHeader = (doc, shop, title, period) => {
  doc.fontSize(16).font("Helvetica-Bold").text(title, { align: "center" });

  doc.moveDown(0.3);
  doc.fontSize(10).font("Helvetica").text(period, { align: "center" });

  doc.moveDown(1);
  doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke();

  doc.moveDown(1);

  doc.font("Helvetica-Bold").text("Shop Details");
  doc.font("Helvetica").fontSize(10);
  doc.text(`Shop Name : ${shop.shopName}`);
  doc.text(`Address   : ${shop.shopAddress}`);
  doc.text(`GSTIN     : ${shop.gstNumber}`);

  doc.moveDown(1);
  doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke();
  doc.moveDown(1);
};

/* ================= TODAY REPORT ================= */
export const downloadTodayReport = async (req, res) => {
  const shop = req.shop;

  // const start = new Date();
  // start.setHours(0, 0, 0, 0);

  // const end = new Date();
  // end.setHours(23, 59, 59, 999);

  const start = getISTStartOfDayUTC();
  const end = getISTEndOfDayUTC();

  const sales = await Sale.aggregate([
    { $match: { shop: shop._id, createdAt: { $gte: start, $lte: end } } },
    {
      $group: {
        _id: null,
        totalSales: { $sum: "$grandTotal" },
        totalBills: { $sum: 1 },
      },
    },
  ]);

  const purchases = await Purchase.aggregate([
    { $match: { shop: shop._id, createdAt: { $gte: start, $lte: end } } },
    { $group: { _id: null, totalPurchases: { $sum: "$totalAmount" } } },
  ]);

  const doc = new PDFDocument({ margin: 40 });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", "attachment; filename=today-report.pdf");
  doc.pipe(res);

  drawHeader(
    doc,
    shop,
    "TODAY'S BUSINESS REPORT",
    `Date: ${new Date().toDateString()}`,
  );

  doc.font("Helvetica-Bold").text("Business Summary");
  doc.moveDown(0.5);

  doc.font("Helvetica").fontSize(11);
  doc.text(`Total Sales      : Rs ${sales[0]?.totalSales || 0}`);
  doc.text(`Total Bills      : ${sales[0]?.totalBills || 0}`);
  doc.text(`Total Purchases  : Rs ${purchases[0]?.totalPurchases || 0}`);

  doc.moveDown(2);
  doc
    .fontSize(9)
    .fillColor("gray")
    .text(`Generated by Vyapaar360 | ${new Date().toLocaleString()}`, {
      align: "center",
    });

  doc.end();
};

export const downloadSalesSummaryReport = async (req, res) => {
  const shop = req.shop;

  const salesAgg = await Sale.aggregate([
    { $match: { shop: shop._id } },
    {
      $group: {
        _id: null,
        totalSales: { $sum: "$grandTotal" },
        totalBills: { $sum: 1 },
        totalGst: { $sum: "$totalGst" },
        maxBill: { $max: "$grandTotal" },
        minBill: { $min: "$grandTotal" },
        avgBill: { $avg: "$grandTotal" },
      },
    },
  ]);

  const data = salesAgg[0] || {};

  const doc = new PDFDocument({ margin: 40 });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    "attachment; filename=sales-summary-report.pdf",
  );
  doc.pipe(res);

  drawHeader(
    doc,
    shop,
    "SALES SUMMARY REPORT",
    `Generated On: ${new Date().toDateString()}`,
  );

  doc.font("Helvetica-Bold").text("Sales Overview");
  doc.moveDown(0.5);

  doc.font("Helvetica").fontSize(11);
  doc.text(`Total Sales       : Rs ${data.totalSales || 0}`);
  doc.text(`Total Bills       : ${data.totalBills || 0}`);
  doc.text(`Total GST         : Rs ${data.totalGst || 0}`);
  doc.text(`Average Bill      : Rs ${(data.avgBill || 0).toFixed(2)}`);
  doc.text(`Highest Bill      : Rs ${data.maxBill || 0}`);
  doc.text(`Lowest Bill       : Rs ${data.minBill || 0}`);

  doc.moveDown(2);
  doc
    .fontSize(9)
    .fillColor("gray")
    .text(`Generated by Vyapaar360 | ${new Date().toLocaleString()}`, {
      align: "center",
    });

  doc.end();
};

/* ================= MONTHLY BUSINESS REPORT ================= */
export const downloadMonthlyReport = async (req, res) => {
  const shop = req.shop;

  // Month range (current month)

  const start = getISTMonthStartUTC();
  const end = new Date();

  const sales = await Sale.aggregate([
    { $match: { shop: shop._id, createdAt: { $gte: start, $lte: end } } },
    {
      $group: {
        _id: null,
        totalSales: { $sum: "$grandTotal" },
        totalBills: { $sum: 1 },
      },
    },
  ]);

  const purchases = await Purchase.aggregate([
    { $match: { shop: shop._id, createdAt: { $gte: start, $lte: end } } },
    { $group: { _id: null, totalPurchases: { $sum: "$totalAmount" } } },
  ]);

  const doc = new PDFDocument({ margin: 40 });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    "attachment; filename=monthly-business-report.pdf",
  );
  doc.pipe(res);

  drawHeader(
    doc,
    shop,
    "MONTHLY BUSINESS REPORT",
    `Period: ${start.toLocaleString("default", {
      month: "long",
    })} ${start.getFullYear()}`,
  );

  doc.font("Helvetica-Bold").text("Monthly Business Summary");
  doc.moveDown(0.5);

  doc.font("Helvetica").fontSize(11);
  doc.text(`Total Sales      : Rs ${sales[0]?.totalSales || 0}`);
  doc.text(`Total Bills      : ${sales[0]?.totalBills || 0}`);
  doc.text(`Total Purchases  : Rs ${purchases[0]?.totalPurchases || 0}`);

  doc.moveDown(2);
  doc
    .fontSize(9)
    .fillColor("gray")
    .text(`Generated by Vyapaar360 | ${new Date().toLocaleString()}`, {
      align: "center",
    });

  doc.end();
};
